### PR TITLE
Totemancer NFT Collection

### PR DESCRIPTION
**Pull request by Totemancer**
Hello Tonkeeper,

we are submitting our NFT collection here. If we’ve missed something in our application please do let us know.

Thank you!

Best,
Totemancer

### CODE REVIEW

**Comment by Totemancer** [comment]
Hello @grishkanaruzhka @mr-tron,

Could you take a look at our submission?

https://github.com/tonkeeper/ton-assets?tab=readme-ov-file#nft-collections

We’ve noticed that mostly Jettons are submitted here, not NFT Collections. If this is no longer maintained, perhaps consider removing the NFT section from this repository to avoid confusion across projects.

**Comment by Totemancer** [comment]
Hello @grishkanaruzhka @mr-tron,

Could we get any feedback on this request? It's been 2 months.

Does this repository no longer support NFT collections?

There are three NFT collections listed:

https://github.com/tonkeeper/ton-assets?tab=readme-ov-file#nft-collections


	•	Telegram usernames (Telegram)
	•	The Gateway (Seems like a ticket to a conference)
	•	Cryptodickbutt (No comment)

If it’s obsolete, please remove the NFT collections from this repository altogether.

Thank you.

**Comment by Totemancer** [comment]
@grishkanaruzhka @mr-tron 

Can you please provide an update on this request?

Thank you.

**Review by KuznetsovNikita — APPROVED** [review]

**Comment by Badmdafka** [comment]
> Hello @grishkanaruzhka @mr-tron,
> 
> Could you take a look at our submission?
> 
> https://github.com/tonkeeper/ton-assets?tab=readme-ov-file#nft-collections
> 
> We’ve noticed that mostly Jettons are submitted here, not NFT Collections. If this is no longer maintained, perhaps consider removing the NFT section from this repository to avoid confusion across projects.





I noticed my friend that nft disappeared from wallet with notification that that was some mistake....114mil tomato / 800,000 dogs ....cat / hamster/ not .....every single participation ended with few of each...🤦   Who are validators and how can when i send 4.5 ton ,they are lost in some space... Even worse, it says that 4.5 ton that i sent are false🤦🤷 Who runs the game ,few validators? Ppl have 15k referrals 🙅 thats wierd very very weird to me...

**Pull request merged**
