### PR TITLE
$FORT verification

### PR DESCRIPTION
**Pull request by ghost**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by kristopulakis** [comment]
Great project (deflationary), liquidity blocked for a year, professional and very honest dev, amazing and creative community.  Dev has a lot of ideas for development, the community believes in him, more and more wallets are arriving, and there are also NFT collections that work closely with the FORT token.  More and more projects want to cooperate with Fort, I highly recommend it 👍

**Comment by Oluwashindaraton** [comment]
$FORT is a great project building on TON, a community reward token with rare NFTs collections driving mass adoption and influx of new wallet on a daily basis. Dev is based and trusted by the community members. I recommend that tonkeeper should verify the $FORT token as more and more investors and partnerships are keen on seeing the verified ticker on fort on tonkeeper.

**Comment by Iammaddies** [comment]
There is no way I will skip this project Had been amazing since I came across it we just need Tonkeeper verification to complete our magnificent project Tonkeeper please verify us

**Comment by Ay1308** [comment]
With utmost sincerity, $FORT is a great and groundbreaking project under $TON Blockchain. I recommend and affirm this recommendation, representing the voice of my entire community that $FORT is a good project with great future

**Comment by mr-tron** [comment]
Please make sure you change the original ones .yaml fiels in directories accounts/, collections/ or jettons/ and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные .yaml файлы в директориях accounts/, collections/ или jettons/ и не трогаете автоматически сгенерированные файлы .json в корне репозитория.

**Comment by Lexichnek** [comment]
$FORT is an excellent project in the $TON blockchain with rare NFT collections, working closely with FORT tokens and community awards. Creative, professional and honest developers. The community believes in him.Tonkipper please confirm this.

**Pull request closed without merging**
