### PR TITLE
Create COSA.yaml

### PR DESCRIPTION
**Pull request by digital-farms**
Dear Tonkeeper Team,  

We would like to kindly request you to consider verifying and approving our token, **$COSA (COSA NOSTRA)**, on your platform. This is a community-created and community-driven token that is part of the TON ecosystem.  

For your convenience, please find the key details about the project below:  

- **Token Address**:  
  [https://tonviewer.com/EQCPqhGBZCOtQUZx-k5DcEGp5XQZkdfQOUfqWK6Z0Lo6vdw7?section=holders](https://tonviewer.com/EQCPqhGBZCOtQUZx-k5DcEGp5XQZkdfQOUfqWK6Z0Lo6vdw7?section=holders)  

- **DEX Listing**:  
  [https://dexscreener.com/ton/eqdwcw3uokv906rbkrtdgeyjqcdrtnvtldnggap9uv2d1isa](https://dexscreener.com/ton/eqdwcw3uokv906rbkrtdgeyjqcdrtnvtldnggap9uv2d1isa)  

- **Community**:  
  [https://t.me/Cosa_Nostra_RU](https://t.me/Cosa_Nostra_RU)  

- **Official Website**:  
  [https://crypto-cosanostra.io/](https://crypto-cosanostra.io/)  

We believe that verification will enhance user trust in the token and make it easier for them to interact with it within the TON ecosystem.  

Thank you in advance for your time and support! Please don’t hesitate to reach out if any additional information is required.  

Sincerely,  
**The COSA NOSTRA Team**

### CODE REVIEW

**Comment by Lumaxzy** [comment]
Привет@Irso007,

Не могли бы вы любезно рассмотреть наш запрос на проверку токена $COSA ? Ваша помощь была бы очень признательна!

Заранее спасибо!

**Comment by Lumaxzy** [comment]
Hello @mr-tron,

Could you kindly review our pull request for the verification of some $COSA token ? Your assistance would be greatly appreciated!

Thank you in advance!

**Comment by Irso007** [comment]
Change the image link in the pull request. Do not use ton.api links in your pull request.

**Comment by Irso007** [comment]
There are some issues with this request:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1435/checks#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 118, in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 6[7](https://github.com/tonkeeper/ton-assets/pull/1435/checks#step:5:8), in merge_jettons
    raise Exception("don't use cache.tonapi.io as image source in %v", j.get("name"))
Exception: ("don't use cache.tonapi.io as image source in %v", 'COSA NOSTRA')

**Comment by digital-farms** [comment]
@Irso007 Thank you for your remark! I've updated the link to the logo, please check it now.

**Pull request merged**
