### PR TITLE
add ICTN - indicaton utility token

### PR DESCRIPTION
**Pull request by alexeypershinov**
Hello, add pls ICTN - indicaton.io utility token

### CODE REVIEW

**Comment by ManMafia** [comment]
Отлично получилось

**Comment by 314567** [comment]
👍🏻👍🏻👍🏻

**Comment by hinowas** [comment]
Good

**Comment by ttbm5** [comment]
ICTN涨涨涨

**Comment by gdhsjen** [comment]
fighting

**Comment by i1992810225** [comment]
漲漲漲

**Comment by avalonzhen** [comment]
a good project team

**Comment by avalonzhen** [comment]
ictn is good
 to moon bro

**Comment by ManMafia** [comment]
С добром Toncoin splinter
UQDZ6BizsaNEDFd534m19sS33g2dMa0Ej9l4cfybi9EGYed9

**Comment by alexeypershinov** [comment]
already verified, thank you

**Pull request closed without merging**
