### PR TITLE
Verification request in /collections Tmail collection

### PR DESCRIPTION
**Pull request by Suplab-commits**
Please make sure you change the original .yaml fields in the accounts/, Collections/ or jettons/ directories and leave the auto-generated .json files in the repository root alone. Also please make sure that you do not use ton.api links in your pull request.
Example pull request:

```yaml
name: the name of your token
description: description of your token
image: "link to your token logo" !!! (don't use ton.api)!!!
address: Address of your token 
symbol: Symbol of your token
websites:
  - "link"
social:
  - "link"
```

Пожалуйста, убедитесь, что вы изменили исходные поля .yaml в каталогах account/, Collections/ или jettons/ и не трогаете автоматически сгенерированные файлы .json в корне репозитория. Так же, пожалуйста, убедитесь, что вы не используете ссылки ton.api в вашем пул реквесте.
Пример пул реквеста:

```yaml
name: имя вашего токена
description: описание вашего токена
image: "ссылка на лого вашего токена" !!! (не используйте ton.api)!!!
address: Адрес вашего токена 
symbol: Сивол вашего токена
websites:
  - "ссылка"
social:
  - "ссылка"
  ```

### CODE REVIEW

**Comment by ghost** [comment]
I don't know any thing about these and need help for it.i don't know what should I do?

**Comment by Suplab-commits** [comment]
> I don't know any thing about these and need help for it.i don't know what should I do?

1) You need to fork this repository.
2) Add a yaml file to the tokens or collections folder - depending on what product you have. You can read the requirements above in the files.
3) Make a pull request to the main branch of this repository.
4) Wait for moderators to check, and then they will tell you if something is wrong

**Comment by Gene090** [comment]
Hello. Have you entered the correct data? Is the address of the collection correct?

**Comment by Suplab-commits** [comment]
> Hello. Have you entered the correct data? Is the address of the collection correct?

Hello, Yes 
image

**Comment by Gene090** [comment]
Hello. Sorry for the misunderstanding. 
Thank you for the information provided. At the moment the collection verification is denied.

**Comment by Suplab-commits** [comment]
> Hello. Sorry for the misunderstanding. Thank you for the information provided. At the moment the collection verification is denied.

Hello, is it possible to find out the reason for the refusal in order to correct the comments and undergo verification again?

**Pull request closed without merging**
