### PR TITLE
Create LEV.yaml

### PR DESCRIPTION
**Pull request by faustyu1**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

### CODE REVIEW

**Comment by faustyu1** [comment]
Up

**Comment by faustyu1** [comment]
up

**Comment by faustyu1** [comment]
up

**Comment by Irso007** [comment]
Unfortunately, verification was denied. Please try again when the token has more holders.

**Pull request closed without merging**
