### PR TITLE
Create $ETN.yaml

### PR DESCRIPTION
**Pull request by jayp89**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by jayp89** [comment]
Create ET Netsa Coin

**Comment by Irso007** [comment]
If you still need verification process, please let us know in this pull request or else it will be closed in a week.

**Comment by jayp89** [comment]
> If you still need verification process, please let us know in this pull request or else it will be closed in a week.

Yes we still need verification

**Comment by salateur** [comment]
I had to revert it since it had some issues 

in "jettons/$ETN.yaml", line 8, column 3
expected <block end>, but found '?'
  in "jettons/$ETN.yaml", line 9, column 3
  
  Please fix it and recreate the PR, sorry for the inconvenience.

**Pull request merged**
