### PR TITLE
Create LEA.yaml

### PR DESCRIPTION
**Pull request by SafeMPCWilliam**
create new token

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by 0xkunty** [comment]
$LEA 


UQA9Ht_QXv7QRKJKwVmr_wPBLbgJdK8sJR6kgHh0vPfNnVQ3

**Comment by Xreunk** [comment]
Wen you airdrop sir my keep holder

Address

EQBIfTGOM4uCx4yYO2yMKgnnICME6Xgobas9EspzwhMynDzz

**Comment by Gembel113** [comment]
Hello, I am a member of the $Lea community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Chilmiif** [comment]
$LEA

UQA5KFQy1lkklS2VN8RxvFBtSC2ER1AHuHQo0tG15Bkog57E
Done sir

**Comment by Gagasg147** [comment]
Hello, I am a member of the $Lea community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

**Comment by Gagasg147** [comment]
Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Chilmiif** [comment]
Yes

Pada Sen, 12 Agu 2024 03.52, Gagasg147 ***@***.***> menulis:

**Comment by Chilmiif** [comment]
Lfg!     $LEA

UQA5KFQy1lkklS2VN8RxvFBtSC2ER1AHuHQo0tG15Bkog57E
Done sir

Pada Sen, 12 Agu 2024 03.59, Chilmi Fawaid ***@***.***>
menulis:

**Comment by Irso007** [comment]
This token has already been verified earlier

**Pull request closed without merging**
