### PR TITLE
Verify Tepe

### PR DESCRIPTION
**Pull request by bull-ape**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by bull-ape** [comment]
Tonkeeper verification for Tepe - $TEPE

**Comment by alazyartist** [comment]
VERIFY $TEPE PLEASE- /blue_frog_army_strong

**Comment by Bablocrypt** [comment]
Dear Ton Keeper Team, 

I trust this message finds you well. 

I am reaching out to discuss $TEPE, a cryptocurrency currently listed on your platform as an “Unverified Token". $TEPE boasts a substantial community comprising over 800 telegram (http://t.me/TEPEONTONN) members, over 1000 followers on twitter (https://twitter.com/ton_tepe) and more than 1000 Token Holders. Notably, the token has achieved an All-Time High (ATH) valuation of $830k, with its current valuation hovering around $500k. 

The project’s team is working extremely hard to keep growing the community, I humbly request your esteemed consideration to verify our token on your platform. 

Thank you for your time and attention to this matter.

**Comment by grishkanaruzhka** [comment]
The request has timed out. If you have any questions about token approval, please contact [@tkgregory](https://t.me/tkgregory) on Telegram for further consideration

**Pull request closed without merging**
