### PR TITLE
Create BLC.yaml

### PR DESCRIPTION
**Pull request by ChuvashiaBulgaria**
Please make sure you change the original .yaml fields in the accounts/, Collections/ or jettons/ directories and leave the auto-generated .json files in the repository root alone. Also please make sure that you do not use ton.api links in your pull request.
Example pull request:

```yaml
name: BulCoin
description: The First National Cryptocurrency of Chuvashia. Instrument of support of Chuvash independence, culture, projects and privatization 
image: "https://raw.githubusercontent.com/ChuvashiaBulgaria/PublicDocs/refs/heads/main/bulcoin.jpg"
address: EQD_tFz9JQRVZNMgy3bzvnzei9deo9qc5NMtumG4_sx1zZRc
symbol: BLC
social:
  - "https://t.me/bulcoin_blc"
  - "https://t.me/chuvash_crypto"
  - "https://x.com/Bulcoin_BLC"
```

Пожалуйста, убедитесь, что вы изменили исходные поля .yaml в каталогах account/, Collections/ или jettons/ и не трогаете автоматически сгенерированные файлы .json в корне репозитория. Так же, пожалуйста, убедитесь, что вы не используете ссылки ton.api в вашем пул реквесте.
Пример пул реквеста:

```yaml
name: BulCoin
description: The First National Cryptocurrency of Chuvashia. Instrument of support of Chuvash independence, culture, projects and privatization 
image: "https://raw.githubusercontent.com/ChuvashiaBulgaria/PublicDocs/refs/heads/main/bulcoin.jpg"
address: EQD_tFz9JQRVZNMgy3bzvnzei9deo9qc5NMtumG4_sx1zZRc
symbol: BLC
social:
  - "https://t.me/bulcoin_blc"
  - "https://t.me/chuvash_crypto"
  - "https://x.com/Bulcoin_BLC"
  ```

### CODE REVIEW

**Comment by ChuvashiaBulgaria** [comment]
Update
+Website

**Comment by Irso007** [comment]
There are some issues with this request:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 176, in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 118, in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 63, in merge_jettons
    raise Exception("invalid keys %s in %s" % (set(j.keys()) - ALLOWED_KEYS, j.get('name')))
Exception: invalid keys {'max_supply'} in Cat Resistance


Please fix it

**Comment by Irso007** [comment]
ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/actions/runs/11999496860/job/33448929232?pr=1305#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 11[8](https://github.com/tonkeeper/ton-assets/actions/runs/11999496860/job/33448929232?pr=1305#step:5:9), in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 63, in merge_jettons
    raise Exception("invalid keys %s in %s" % (set(j.keys()) - ALLOWED_KEYS, j.get('name')))
Exception: invalid keys {'max_supply'} in BulCoin

**Comment by ChuvashiaBulgaria** [comment]
fixed

**Pull request merged**
