### PR TITLE
Create CRT.yaml

### PR DESCRIPTION
**Pull request by devcryptaskr**
name: Cryptaskr Token
description: Unlock rewards with Cryptaskr! Complete tasks to earn points, convert them into CRT tokens, and swap for TON.
image: "https://token.cryptaskr.com/token-image.png"
address: 0:1b75e30a64ae5bcca53a928e9af70303a5b1223f02bf08e6bfdb41443dcb295d
symbol: CRT
websites:
  - “https://cryptaskr.com/”
social:
  - "https://x.com/cryptaskr"
  - “https://t.me/cryptaskr”
  - “https://www.youtube.com/channel/UC_329QsRrTQ9x7XwdNdReUQ”
  - "https://t.me/cryptaskrannouncement”
  - “https://t.me/Cryptaskr_bot/CRT”

### CODE REVIEW

**Comment by Irso007** [comment]
There are some issues with this request:

in "jettons/CRT.yaml", line 12, column 5
found unexpected end of stream
  in "jettons/CRT.yaml", line 14, column 1


Please fix it

**Review by devcryptaskr — COMMENTED** [review]
Updated

**Comment by devcryptaskr** [comment]
Good day sir, 

i have pushed an update. 
can you help me review it?

https://github.com/tonkeeper/ton-assets/pull/1291/commits/99f5347d7ba8d5a7b678816035e69b67dbb0273f

**Comment by devcryptaskr** [comment]
> There are some issues with this request:
> 
> in "jettons/CRT.yaml", line 12, column 5 found unexpected end of stream in "jettons/CRT.yaml", line 14, column 1
> 
> Please fix it

Good day sir,

i have pushed an update.
can you help me review it?

https://github.com/tonkeeper/ton-assets/pull/1291/commits/99f5347d7ba8d5a7b678816035e69b67dbb0273f

**Comment by Irso007** [comment]
There are some issues with this request:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1291/checks#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 11[8](https://github.com/tonkeeper/ton-assets/pull/1291/checks#step:5:9), in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 63, in merge_jettons
    raise Exception("invalid keys %s in %s" % (set(j.keys()) - ALLOWED_KEYS, j.get('name')))
Exception: invalid keys {'max_supply'} in Cat Resistance

**Comment by devcryptaskr** [comment]
> There are some issues with this request:
> 
> ERROR:root:failed to get megaton assets Traceback (most recent call last): File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1291/checks#step:5:7), in main() File "/home/runner/work/ton-assets/ton-assets/generator.py", line 11[8](https://github.com/tonkeeper/ton-assets/pull/1291/checks#step:5:9), in main jettons = merge_jettons() File "/home/runner/work/ton-assets/ton-assets/generator.py", line 63, in merge_jettons raise Exception("invalid keys %s in %s" % (set(j.keys()) - ALLOWED_KEYS, j.get('name'))) Exception: invalid keys {'max_supply'} in Cat Resistance

Good day sir, 

i have an update for the file

https://github.com/tonkeeper/ton-assets/pull/1291/commits/efb49e5caa24fe56ad3f4846646f3f9c3b9a215d

hope this fixes the issue..

or is there a way for us to check if there are error in our commits before updating?

Thank you for the response

**Pull request merged**
