### PR TITLE
Create TONKING.yaml

### PR DESCRIPTION
**Pull request by gaurav-gupta**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by shubhamparamhans** [comment]
Hi is there any timeline for approval?

**Comment by shubhamparamhans** [comment]
@mr-tron is there anything else required to merge this?

**Comment by shubhamparamhans** [comment]
Can somebody comment here if anything else is required to get this done?

**Comment by gaurav-gupta** [comment]
@mr-tron Please let us know, if there is any mistake in our pull request or TONKING.YAML. We are waiting since last week and no update yet.

**Comment by gaurav-gupta** [comment]
Another pull request already merged

**Pull request closed without merging**
