### PR TITLE
BRK.yaml

### PR DESCRIPTION
**Pull request by catus98**
Dear Tonkeeper Team,

We are reaching out to kindly request the verification of our token, $BRK, on your platform. This token embodies a bold and stylish meme project designed to stand out within the TON ecosystem and beyond.

Here are the essential details for your consideration:

Token Address:
https://tonviewer.com/EQAktQROTvFgjjdGVdbjvrF48-rod9Qw2Vwfp5GoT6F1UYiu

DEX Listing:
https://dexscreener.com/ton/EQAhtAPK0hdz1gfXMVshvTx2UVKq4ayPhiKb1L7Gj2--9-s0

Website Links:

[Telegram](https://t.me/barokuz)
[Twitter Profile](https://x.com/barokuz)
Verification will greatly assist in fostering user trust and accessibility for $BRK, further strengthening its position within the TON community.

Thank you for considering our request. Should you need any additional information, please don’t hesitate to let us know.

Warm regards,
BAROKUZ Team

### CODE REVIEW

**Comment by Irso007** [comment]
Change the image link in the pull request. Do not use ton.api links in your pull request.

**Comment by Irso007** [comment]
There are some issues with this request:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1640/checks#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 118, in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 6[7](https://github.com/tonkeeper/ton-assets/pull/1640/checks#step:5:8), in merge_jettons
    raise Exception("don't use cache.tonapi.io as image source in %v", j.get("name"))
Exception: ("don't use cache.tonapi.io as image source in %v", 'Barokuz')

Please fix it

**Review by Frank40Rd — APPROVED** [review]

**Comment by Frank40Rd** [comment]
This pull request includes a new entry in the `jettons/brk.yaml` file. The entry adds details about a token named Barokuz.

Details added:

* [`name`](diffhunk://#diff-be28b2b46a83117cf2210f255530c30c1aaa037747f6b0d8f233cd3669d2545fR1-R9): Barokuz
* [`description`](diffhunk://#diff-be28b2b46a83117cf2210f255530c30c1aaa037747f6b0d8f233cd3669d2545fR1-R9): Ben Değil Biziz Hepimiz Barokuz
* [`image`](diffhunk://#diff-be28b2b46a83117cf2210f255530c30c1aaa037747f6b0d8f233cd3669d2545fR1-R9): URL to the token's image
* [`address`](diffhunk://#diff-be28b2b46a83117cf2210f255530c30c1aaa037747f6b0d8f233cd3669d2545fR1-R9): Token's address
* [`symbol`](diffhunk://#diff-be28b2b46a83117cf2210f255530c30c1aaa037747f6b0d8f233cd3669d2545fR1-R9): BRK
* [`decimals`](diffhunk://#diff-be28b2b46a83117cf2210f255530c30c1aaa037747f6b0d8f233cd3669d2545fR1-R9): 9
* [`social`](diffhunk://#diff-be28b2b46a83117cf2210f255530c30c1aaa037747f6b0d8f233cd3669d2545fR1-R9): Links to Barokuz's Telegram and X (formerly Twitter) pages

**Comment by catus98** [comment]
Dear Tonkeeper Team,

requested changes are done and updated.
waiting for your approval.

Warm regards,
BAROKUZ Team

**Comment by Frank40Rd** [comment]
> Es gibt einige Probleme mit dieser Anfrage:
> 
> FEHLER: root: Megatonnen-Assets konnten nicht abgerufen werden. Traceback (letzter Aufruf zuletzt): Datei "/home/runner/work/ton-assets/ton-assets/generator.py", Zeile 17 [6](https://github.com/tonkeeper/ton-assets/pull/1640/checks#step:5:7) , in main() Datei "/home/runner/work/ton-assets/ton-assets/generator.py", Zeile 118, in main jettons = merge_jettons() Datei "/home/runner/work/ton-assets/ton-assets/generator.py", Zeile 6 [7](https://github.com/tonkeeper/ton-assets/pull/1640/checks#step:5:8) , in merge_jettons Ausnahme auslösen ("verwende cache.tonapi.io nicht als Bildquelle in %v", j.get("name")) Ausnahme: ("verwende cache.tonapi.io nicht als Bildquelle in %v", ‚Barokuz‘)
> 
> Bitte beheben Sie das Problem

Können sie mir bitte dabei helfen , ich weiß nicht wie ich es machen soll . wäre mega lieb von ihnen . mfg

**Comment by Gene090** [comment]
Hello. Your request has been merged.

**Pull request merged**
