### PR TITLE
Create RealShahnameh.yaml

### PR DESCRIPTION
**Pull request by Shahnameh-TON**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Review by Fart10 — COMMENTED** [review]
👌

**Comment by grishkanaruzhka** [comment]
At the moment we cannot approve your token
Let's come back to this issue later

**Comment by Shahnameh-TON** [comment]
> At the moment we cannot approve your token Let's come back to this issue later

What is the reason?

**Comment by XS227** [comment]
Thank you for reviewing our submission.

Could you please provide more details on why the token wasn't approved?

We would like to understand the specific changes required to meet your criteria.

Your guidance will help us proceed effectively.
With my best regards
Shahnameh / CEO

**Pull request closed without merging**
