### PR TITLE
Create BIP.yaml

### PR DESCRIPTION
**Pull request by Invisiblieboy**
name: BaltInvestProject
description: The Best of The Best
image: https://raw.githubusercontent.com/Invisiblieboy/BIP_utils/main/BIP.png
address: 0:6fc7606752ffebad72f732e6be9ce0b6901a7c183ea55bb7d1a8598b900cf3bd
symbol: BIP
social:
  - https://t.me/BIPholders
  - https://t.me/BIPuserchat
admin:
  - https://t.me/spiwt

### CODE REVIEW

**Comment by Irso007** [comment]
The request is not complete. Please note the rules for submitting a request:

Please make sure you change the original .yaml fields in the accounts/, Collections/ or jettons/ directories and leave the auto-generated .json files in the repository root alone. Also please make sure that you do not use ton.api links in your pull request.

Example pull request:

name: the name of your token
description: description of your token
image: "link to your token logo" !!! (don't use ton.api)!!!
address: Address of your token
symbol: Symbol of your token
websites:
 - "link"
social:
 - "link"

**Comment by Irso007** [comment]
There is also an error in the file:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[5](https://github.com/tonkeeper/ton-assets/pull/1272/checks#step:5:6), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 118, in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line [6](https://github.com/tonkeeper/ton-assets/pull/1272/checks#step:5:7)7, in merge_jettons
    raise Exception("don't use cache.tonapi.io as image source in %v", j.get("name"))
Exception: ("don't use cache.tonapi.io as image source in %v", 'BaltInvestProject')

**Comment by Irso007** [comment]
If your request is relevant, please make the changes we wrote above. If there are no changes, your request will be closed in a week.

**Comment by Irso007** [comment]
If your request is relevant, create a new request.

**Comment by Invisiblieboy** [comment]
> If your request is relevant, create a new request.

Ok, I made a nuw request #1460

**Pull request closed without merging**
