### PR TITLE
Create DUROV

### PR DESCRIPTION
**Pull request by DurovToken**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by Governor-HQ** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

**Comment by Ntonghoelemi** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. I'll like to state that, We do not suffer from lack of liquidity and these are the current token details.

**Comment by Georgebuba** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by HairGel123** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Sampresh-crypto** [comment]
Greetings, I am a member of the $DUROV community, this is a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token.
We do not in any way suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors. Thank you!

**Comment by Skay124** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors. Thanks

**Comment by Deevibes6680** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Annyjnr** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Danielsjnr5590** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by leandrohrusso** [comment]
Hello, I am a member of the [$DUROV](https://twitter.com/search?q=%24DUROV&src=cashtag_click) community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by TonyAkinsWritesCrypto** [comment]
Hello, my name is Tony,a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by brakke9000** [comment]
Hello, my name is Bram and I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Crystalluv** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by ZONIA001** [comment]
Hello, I am a member of the DUROV community. Our community holds a legitimate token that meets the liquidity and market cap requirements to become a verified token. We do not face any issues of liquidity and here are the current token details. 

We request you take necessary action to ensure that new investors are not affected by any barrier to entry. As investors, we want to ensure that everyone has an equal opportunity to invest in our token.

**Comment by luminousbabe** [comment]
Hello, I am a member of the [$DUROV](https://twitter.com/search?q=%24DUROV&src=cashtag_click) community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

**Comment by luminousbabe** [comment]
Hello, I am a member of the [$DUROV](https://twitter.com/search?q=%24DUROV&src=cashtag_click) community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Alhassan33** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

**Comment by Elochukwu345** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

**Comment by Basic004** [comment]
Hello, I am a member of the $DUROV community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We do not suffer from lack of liquidity and these are the current token details.

**Comment by grishkanaruzhka** [comment]
The request has timed out. If you have any questions about token approval, please contact [@tkgregory](https://t.me/tkgregory) on Telegram for further consideration

**Pull request closed without merging**
