### PR TITLE
Adding new token TAXI

### PR DESCRIPTION
**Pull request by KotNaplakal**
Added YAML file for token TAXI.

### CODE REVIEW

**Comment by tirepic** [comment]
Please hurry up with the verification of the TAXI token, we’re eagerly waiting.

**Comment by moisei25** [comment]
TAXI to the moon, go go go verification✈️🥸

**Comment by yavkontente** [comment]
Hooray, I waited for the day when TAXI is verified in Tonkeeper 🚀

**Comment by Mohito777** [comment]
Good job

**Comment by salateur** [comment]
Hello, you need to add socials, change the img (you can't use cache tonapi.io as image host), only after checking everything, we can continue the process.

**Comment by KotNaplakal** [comment]
> Hello, you need to add socials, change the img (you can't use cache tonapi.io as image host), only after checking everything, we can continue the process.

Good day! Added Telegram channel to description and replaced the link to the logo. Thank you!

**Pull request merged**
