### PR TITLE
Create TETRIX.yaml

### PR DESCRIPTION
**Pull request by samlowry**
Added info about TETRIX - 1st AI meme token @ TON (acc. to https://x.com/Tleubayev/status/1859539670977167468 )

```yaml
name: TETRIX
address: EQC-OHxhI9r5ojKf6QMLFjhQrKoawN1thhHFCvImINhfK40C
description: "TETRIX - First AI-born token in control 🤖 Join the future!"
image: "https://dd.dexscreener.com/ds-data/tokens/ton/eqc-ohxhi9r5ojkf6qmlfjhqrkoawn1thhhfcviminhfk40c.png"
symbol: TETRIX
social:
  - "https://t.me/T3TR1Xc01n"
  - "https://x.com/T3TR1Xc01n"
```

### CODE REVIEW

**Comment by Irso007** [comment]
The website is incorrectly specified.

**Comment by samlowry** [comment]
> The website is incorrectly specified.

What do you mean? We control tetrix.ton domain and now we work on releasing Tetrix inner agents chat vizualisation.

**Comment by MXzander** [comment]
e

**Comment by samlowry** [comment]
> The website is incorrectly specified.

hello! I removed website value for now - till we have it online. pls, merge branch when you will have time

**Comment by Gene090** [comment]
Hello. Your request has been merged.

**Pull request merged**
