### PR TITLE
INVITE Verification

### PR DESCRIPTION
**Pull request by lcl6659**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by grishkanaruzhka** [comment]
@lcl6659 remove quotes from lines 1,3,5

**Comment by lcl6659** [comment]
> @lcl6659 remove quotes from lines 1,3,5

Thank you for your reply. I have removed the quotes from lines 1, 3, and 5.

**Comment by lcl6659** [comment]
@grishkanaruzhka Thank you for your reply. I have removed the quotes from lines 1, 3, and 5.

**Comment by lcl6659** [comment]
@grishkanaruzhka Are there any other issues? Why hasn't it been merged yet?

**Comment by ghost** [comment]
Iam sorry

Pada Jum, 23 Agu 2024 11.22, Nick Li ***@***.***> menulis:

**Comment by ghost** [comment]
https://github.com/UXLINK/ton-assets/commits?author=lcl6659

**Comment by lcl6659** [comment]
> https://github.com/UXLINK/ton-assets/commits?author=lcl6659

I'm sorry, I didn't quite understand. Is there something wrong with this submission? Do I need to do something?

**Comment by Gene090** [comment]
Hello! Please, let us know if the request is still relevant, or it will be closed in a week.
Sorry it took so long to review the request.

**Pull request closed without merging**
