### PR TITLE
Update Binance address

### PR DESCRIPTION
**Pull request by aleksej-paschenko**

### CODE REVIEW

**Comment by ghost** [comment]
521322

**Review by ghost — COMMENTED** [review]
521322

**Comment by ghost** [comment]
https://ton.cx/address/EQD_4XXRv9RhthsiFJWCRlAooMXkIlWTQI2khoxSDWF5EZVe

**Comment by PearlsAmos** [comment]
0c346820851a17b86d5d3f5f4f0db2491db715b6

**Pull request merged**
