### PR TITLE
Create GPX.yaml

### PR DESCRIPTION
**Pull request by Feel1power**
Please make sure you change the original .yaml fields in the accounts/, Collections/ or jettons/ directories and leave the auto-generated .json files in the repository root alone. Also please make sure that you do not use ton.api links in your pull request.
Example pull request:

```yaml
name: the name of your token
description: description of your token
image: "link to your token logo" !!! (don't use ton.api)!!!
address: Address of your token 
symbol: Symbol of your token
websites:
  - "link"
social:
  - "link"
```

Пожалуйста, убедитесь, что вы изменили исходные поля .yaml в каталогах account/, Collections/ или jettons/ и не трогаете автоматически сгенерированные файлы .json в корне репозитория. Так же, пожалуйста, убедитесь, что вы не используете ссылки ton.api в вашем пул реквесте.
Пример пул реквеста:

```yaml
name: имя вашего токена
description: описание вашего токена
image: "ссылка на лого вашего токена" !!! (не используйте ton.api)!!!
address: Адрес вашего токена 
symbol: Сивол вашего токена
websites:
  - "ссылка"
social:
  - "ссылка"
  ```

### CODE REVIEW

**Comment by Irso007** [comment]
There are some issues with this request:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1453/checks#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 118, in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line [7](https://github.com/tonkeeper/ton-assets/pull/1453/checks#step:5:8)8, in merge_jettons
    raise Exception("invalid image field type %s" % j.get("name"))
Exception: invalid image field type Golden Pixel

Please fix it

**Comment by Feel1power** [comment]
ready

**Comment by Gene090** [comment]
Hi. The error persists, please change the link. Also, it would be good to add information about the project in the description. Thank you!

**Comment by Feel1power** [comment]
Hi. Link changed, description added, sir

**Comment by Irso007** [comment]
The problem is not resolved:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1453/checks#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 118, in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line [7](https://github.com/tonkeeper/ton-assets/pull/1453/checks#step:5:8)8, in merge_jettons
    raise Exception("invalid image field type %s" % j.get("name"))
Exception: invalid image field type Golden Pixel

**Comment by Irso007** [comment]
Again:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1453/checks?notification_referrer_id=NT_kwDOCzV5YLUxMzU1OTIzODc5NDoxODgwNTM4NTY#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 118, in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line [7](https://github.com/tonkeeper/ton-assets/pull/1453/checks?notification_referrer_id=NT_kwDOCzV5YLUxMzU1OTIzODc5NDoxODgwNTM4NTY#step:5:8)8, in merge_jettons
    raise Exception("invalid image field type %s" % j.get("name"))
Exception: invalid image field type Golden Pixel

**Comment by Gene090** [comment]
Hello. Please change the link to the image, when I follow it, it opens the site.  
The error persists.

**Comment by Gene090** [comment]
Hello. After reviewing the information, we have to inform you that at the moment verification is denied.

**Pull request closed without merging**
