### PR TITLE
Donkeyton for Tonkeeper Verification. thank you

### PR DESCRIPTION
**Pull request by donkeyton**
Please make sure you change the original .yaml fields in the accounts/, Collections/ or jettons/ directories and leave the auto-generated .json files in the repository root alone. Also please make sure that you do not use ton.api links in your pull request.
Example pull request:

```yaml
name: Donkeyton
symbol: DONT
```

### CODE REVIEW

**Comment by donkeyton** [comment]
How long does it take for a maintainer to approve a pull request?

**Comment by donkeyton** [comment]
Please check. thank you

**Comment by Irso007** [comment]
Incorrect data in pull request

If you want to pass verification for a token, then create a request only for the token, and not for the address and collections.

**Comment by donkeyton** [comment]
hello What should I mention in the pull request?

**Comment by donkeyton** [comment]
Can I modify this request? Which items are currently bugged? Thank you for
your guidance

**Comment by donkeyton** [comment]
hello What should I mention in the pull request?
Just the name and symbol? Like the changes I just made, right?

**Comment by donkeyton** [comment]
> Incorrect data in pull request
> 
> If you want to pass verification for a token, then create a request only for the token, and not for the address and collections.

I changed the request as you said.

**Comment by donkeyton** [comment]
> Incorrect data in pull request
> 
> If you want to pass verification for a token, then create a request only for the token, and not for the address and collections.

Please help solve the problem. We are having issues with investors regarding the timing of investment and airdrop distribution due to token not being approved. Please

**Pull request closed without merging**
