### PR TITLE
Create CSC.yaml

### PR DESCRIPTION
**Pull request by brtec**
Complete Coin and Project Details At:
https://t.me/cloudsmartcoin/14

name: CloudSmart
description: "CloudSmart Coin— CloudQi's SmartAssistant platform and CloudSmart Coin (CSC) aim to make Web3 accessible globally, focusing on Portuguese and Spanish speakers at starts. We're committed to breaking down language and cultural barriers, enabling these communities to engage with Web3 effortlessly and securely. Through user-friendly interfaces and multilingual support, we're paving the way for a truly global and accessible Web3 future."
image: "https://hub.cloudqi.com.br/cloudsmart.png"
address: "EQCnZ6w7TFdawajAsRe8op82L1OUa2qviCoceZdZ-BYRBTSu"
symbol: CSC
decimals: 9

websites:
  - "https://cloudqi.com.br/"

social:
  - "https://t.me/chatcloudsmart"
  - "https://t.me/cloudsmartcoin"
  - "https://t.me/cloudsmartcoinpt"
  - "https://x.com/cqiofc"

### CODE REVIEW

**Comment by brtec** [comment]
https://coinmarketcap.com/dexscan/ton/EQBLTOgBgXkCa0c6F2_Tc-kVP3OG2a5ShTX_5JXlDI2Q3rQ8

**Comment by brtec** [comment]
Now officially at company website awaiting approval
https://www.cloudqi.com.br/#cloudsmart

> Complete Coin and Project Details At:
> https://t.me/cloudsmartcoin/14
> 
> name: CloudSmart
> description: "CloudSmart Coin— CloudQi's SmartAssistant platform and CloudSmart Coin (CSC) aim to make Web3 accessible globally, focusing on Portuguese and Spanish speakers at starts. We're committed to breaking down language and cultural barriers, enabling these communities to engage with Web3 effortlessly and securely. Through user-friendly interfaces and multilingual support, we're paving the way for a truly global and accessible Web3 future."
> image: "https://hub.cloudqi.com.br/cloudsmart.png"
> address: "EQCnZ6w7TFdawajAsRe8op82L1OUa2qviCoceZdZ-BYRBTSu"
> symbol: CSC
> decimals: 9
> 
> websites:
>   - "https://cloudqi.com.br/"
> 
> social:
>   - "https://t.me/chatcloudsmart"
>   - "https://t.me/cloudsmartcoin"
>   - "https://t.me/cloudsmartcoinpt"
>   - "https://x.com/cqiofc"

**Comment by Gene090** [comment]
Tonkeeper reserves the right to refuse token verification.

**Comment by brtec** [comment]
For what ? I'm working hard here

**Pull request closed without merging**
