### PR TITLE
commit a new jetton

### PR DESCRIPTION
**Pull request by GaodeCoin**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by GaodeCoin** [comment]
We created this jetton on Ton blockchain, and our customers have already keep it, but it's told Unverified Token in some ton wallet, such as tonkeeper. Son we searched some  official information and commit files here.I think we can make a big contribution to ton blockchain.If you need more information, you can contact me with telegram accout(https://t.me/gaodeTV). Watting for your response.Thanks very much!

**Review by GaodeCoin — COMMENTED** [review]
changes is all right

**Review by MoeGawad10 — APPROVED** [review]

**Comment by GaodeCoin** [comment]
thanks very much

**Comment by GaodeCoin** [comment]
thanks very much, I'll change it with your opinion and pull again

**Pull request closed without merging**
