### PR TITLE
Create MISTRESS.yaml

### PR DESCRIPTION
**Pull request by MistressOnTon**
Mistress is the dominatrix woman of $TON blockchain, spanking the bads boys to make them good boys.

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by Vladislav22513** [comment]
We need this !

**Comment by guPEKTOP** [comment]
Let it happen faster

**Comment by NatataGore** [comment]
Hello, I am a member of the $MISTRESS community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We would love to see our token as verified on your esteemed wallet. 

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Comment by Eduard96** [comment]
Hello, I am a member of the $MISTRESS community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We would love to see our token as verified on your esteemed wallet. 

Please take action so that we investors are not affected by the barrier to entry for new investors.

**Pull request merged**
