### PR TITLE
UNICJ Token

### PR DESCRIPTION
**Pull request by masovskiy**
```yaml
name: UniCoin Jetton
description: Token for working with DApps from UniMas
image: "https://i.ibb.co/G00Fd8D/avatar-Head3-1.png"
address: 0:a7a7dac07d52c9f769b372876eea1b84bb4c0b7b86d585db1dc98fdbc0b2b6a5
symbol: UNICJ
websites:
  - "https://my.bio/unicj"
social:
  - "https://t.me/masov_mas"
  - "https://t.me/unicoin_tg"

  ```

### CODE REVIEW

**Comment by masovskiy** [comment]
Day 1

**Review by masovskiy — COMMENTED** [review]
Day 1

**Comment by Gene090** [comment]
Tonkeeper reserves the right to refuse token verification.

**Comment by masovskiy** [comment]
Why?

**Pull request closed without merging**
