### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by tokencreate**
Please make sure you change the original .yaml fields in the accounts/, Collections/ or jettons/ directories and leave the auto-generated .json files in the repository root alone. Also please make sure that you do not use ton.api links in your pull request.
Example pull request:

```yaml
name: the name of your token
description: description of your token
image: "link to your token logo" !!! (don't use ton.api)!!!
address: Address of your token 
symbol: Symbol of your token
websites:
  - "link"
social:
  - "link"
```

Пожалуйста, убедитесь, что вы изменили исходные поля .yaml в каталогах account/, Collections/ или jettons/ и не трогаете автоматически сгенерированные файлы .json в корне репозитория. Так же, пожалуйста, убедитесь, что вы не используете ссылки ton.api в вашем пул реквесте.
Пример пул реквеста:

```yaml
name: имя вашего токена
description: описание вашего токена
image: "ссылка на лого вашего токена" !!! (не используйте ton.api)!!!
address: Адрес вашего токена 
symbol: Сивол вашего токена
websites:
  - "ссылка"
social:
  - "ссылка"
  ```

### CODE REVIEW

**Comment by tokencreate** [comment]
Anyone can review?

**Review by hossen71 — APPROVED** [review]
59a3c17847d85bfec348d99a5df9527b194f7d11

**Comment by hossen71** [comment]
good

**Comment by tokencreate** [comment]
> good

I need to merge it back to main or not?

**Comment by tokencreate** [comment]
> good

https://github.com/tonkeeper/ton-assets/pull/1265/commits/f9111d814f33cf7f8d94773c38be3c8d478644c7

**Comment by tokencreate** [comment]
> > good
> 
> [f9111d8](https://github.com/tonkeeper/ton-assets/commit/f9111d814f33cf7f8d94773c38be3c8d478644c7)

https://github.com/tonkeeper/ton-assets/pull/1265/commits

**Review by SadDoge-audio — CHANGES_REQUESTED** [review]
Sad Doge ⛽️ https://audio.gaspump.tg/SADDOGE_1.mp3 | why i`m sad?

**Review by naxoootcnjncgjnnxfhjjv — COMMENTED** [review]
lloEh

**Review by hossen71 — APPROVED** [review]
59a3c17847d85bfec348d99a5df9527b194f7d11

**Comment by hossen71** [comment]
659ada86f763d45d2b8cf3b0e7bf376f3ee4fbb8

**Comment by hossen71** [comment]
d1ec9041910e2b6cdef739428dee5359e6aeeafd

**Comment by hossen71** [comment]
f9111d814f33cf7f8d94773c38be3c8d478644c7

**Comment by hossen71** [comment]
59a3c17847d85bfec348d99a5df9527b194f7d11

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
This pull request includes the addition of a new account and a new jetton configuration. The most important changes are:

### New Account Addition:
* Added a new account entry for "RealShahnameh" in `accounts.json`.

### New Jetton Configuration:
* Created a new `REAL.yaml` file for the "RealShahnameh" jetton, including its name, description, image, address, symbol, websites, and social links.

**Comment by Shahnameh-TON** [comment]
> This pull request includes the addition of a new account and a new jetton configuration. The most important changes are:
> 
> ### New Account Addition:
> * Added a new account entry for "RealShahnameh" in `accounts.json`.
> 
> ### New Jetton Configuration:
> * Created a new `REAL.yaml` file for the "RealShahnameh" jetton, including its name, description, image, address, symbol, websites, and social links.

Thank you for the awesome help to this. I will make it right now

**Review by hossen71 — CHANGES_REQUESTED** [review]
59a3c17847d85bfec348d99a5df9527b194f7d11

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
This pull request introduces a new entry to the `accounts.json` file and adds a new configuration file for the `RealShahnameh` token. The most important changes are:

Additions to `accounts.json`:

* Added a new account entry for `RealShahnameh` with the specified address and name.

New configuration for `RealShahnameh` token:

* Created `jettons/REAL.yaml` with details about the `RealShahnameh` token, including its name, description, image, address, symbol, and associated websites and social media links.

**Comment by Shahnameh-TON** [comment]
> This pull request introduces a new entry to the `accounts.json` file and adds a new configuration file for the `RealShahnameh` token. The most important changes are:
> 
> Additions to `accounts.json`:
> 
> * Added a new account entry for `RealShahnameh` with the specified address and name.
> 
> New configuration for `RealShahnameh` token:
> 
> * Created `jettons/REAL.yaml` with details about the `RealShahnameh` token, including its name, description, image, address, symbol, and associated websites and social media links.

I will add a new account entry for realshahnameh
 and i will config new for realshahnameh

**Review by hossen71 — CHANGES_REQUESTED** [review]
659ada86f763d45d2b8cf3b0e7bf376f3ee4fbb8

**Comment by hossen71** [comment]
> > good
> 
> I need to merge it back to main or not?

 yes

**Comment by naxoootcnjncgjnnxfhjjv** [comment]
### >

**Pull request closed without merging**
