### PR TITLE
SoG Coin

### PR DESCRIPTION
**Pull request by gru2007**
We are token for Arma 3 Star Wars server. When it will be launched you will be able to get it by playing on our server and completing tasks.
We will sell exclusive NFTs only using this token.

### CODE REVIEW

**Comment by mr-tron** [comment]
please notify when you go to prod

**Review by tangjeff1995 — APPROVED** [review]

**Comment by gru2007** [comment]
> please notify when you go to prod

@mr-tron closer to end of February we want give out some SOGs to our administration for their work. Public gaining of token will be in March I suppose, there is some tech difficulties.
So maybe you approve token now, then we will have one problem less?

**Comment by gru2007** [comment]
@mr-tron @tangjeff1995 how can I notify you?

**Review by gru2007 — COMMENTED** [review]
Launch in march

**Comment by gru2007** [comment]
Launch in few days

**Review by tangjeff1995 — APPROVED** [review]

**Review by tangjeff1995 — APPROVED** [review]

**Comment by gru2007** [comment]
@mr-tron merge please

**Review by tangjeff1995 — APPROVED** [review]

**Pull request closed without merging**
