### PR TITLE
Main

### PR DESCRIPTION
**Pull request by HPODN10i**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by Hlvng2024** [comment]
Bullish

**Review by Hlvng2024 — APPROVED** [review]

**Comment by Backalfc** [comment]
Very bullish

**Comment by Backalfc** [comment]
Hello, I am a member of the $BITCOIN community, a legitimate community with a token that meets the liquidity and market cap parameters to become a verified token. We would love to see our token as verified on your esteemed wallet.

**Review by Hlvng2024 — APPROVED** [review]

**Comment by grishkanaruzhka** [comment]
The request has timed out. If you have any questions about token approval, please contact [@tkgregory](https://t.me/tkgregory) on Telegram for further consideration

**Pull request closed without merging**
