### PR TITLE
Add SuperWonton in SW.yaml

### PR DESCRIPTION
**Pull request by WontonOrg**
Pull request content:

```yaml
name: SuperWonton
description: "$SW Token - Super WONTON 🥟 🔥 Born to Cook, So LFC! Created by the WONTON Fam, $SW showcases the superpower of WONTON and the strength of the community. 💪"
image: "https://dd.dexscreener.com/ds-data/tokens/ton/eqbgi-rl6szhjp5rtoqg0jlwsgph4rnvku6eand1yvouzmpg.png"
address: "EQBgI-rl6SzhJp5Rtoqg0JlWsgPH4rnVkU6EAnD1yvOuzMPG"
symbol: SW
websites:
  - "https://x.com/SuperwontonOrg"
  - "https://t.me/superwonton"
social:
  - "https://x.com/SuperwontonOrg"
  - "https://t.me/superwonton"
```

### CODE REVIEW

**Comment by ghost** [comment]
name: SuperWonton
description: $SW Token - Super WONTON 🥟
image: "https://dd.dexscreener.com/ds-data/tokens/ton/eqbgi-rl6szhjp5rtoqg0jlwsgph4rnvku6eand1yvouzmpg.png"
address: "EQBgI-rl6SzhJp5Rtoqg0JlWsgPH4rnVkU6EAnD1yvOuzMPG"
symbol: SW
websites:
  - "https://x.com/SuperwontonOrg"
social:
  - "https://x.com/SuperwontonOrg"

**Comment by Irso007** [comment]
Does the token have a website or other social networks?
Where else can I find information about your token besides the x.com website?

**Comment by WontonOrg** [comment]
> Does the token have a website or other social networks? Where else can I find information about your token besides the x.com website?

It's a fan token created by WONTON supporters on TON. It's not the official WONTON token, but to show our support to the project.

WONTON Socials
Bot URL: [@WontonOrgBot] https://t.me/WontonOrgBot
Telegram Channel: https://t.me/WONTONorg
Twitter Page: https://x.com/wontonorg

**Comment by Irso007** [comment]
Tonkeeper reserves the right to refuse token verification.

**Pull request closed without merging**
