### PR TITLE
Create ArixDEX.yaml

### PR DESCRIPTION
**Pull request by arixexchangebot**

### CODE REVIEW

**Comment by ghost** [comment]
521322

**Comment by ghost** [comment]
521322

**Review by ghost — APPROVED** [review]
521322

**Review by Nwachimereze1-hub — COMMENTED** [review]
Contact internation

**Comment by Jimmy-12344780** [comment]
Please cheak my transaction ?

**Comment by Irso007** [comment]
If you still need verification process, please let us know in this pull request or else it will be closed in a week.

**Comment by Irso007** [comment]
You need to change the link to your token logo. Please make sure that you do not use ton.api links in your pull request

**Comment by Irso007** [comment]
You need to edit your file and replace the link directly in it.

**Comment by Jimmy-12344780** [comment]
oh

**Pull request merged**
