### PR TITLE
Create TGXP.yaml

### PR DESCRIPTION
**Pull request by ncsft**
TGXP

### CODE REVIEW

**Comment by Irso007** [comment]
If you still need verification process, please let us know in this pull request or else it will be closed in a week.

**Comment by ncsft** [comment]
> If you still need verification process, please let us know in this pull request or else it will be closed in a week.

Still actual

**Comment by Irso007** [comment]
You need to change the link to your token logo. Please make sure that you do not use ton.api links in your pull request

**Comment by ncsft** [comment]
> You need to change the link to your token logo. Please make sure that you do not use ton.api links in your pull request

Done

**Pull request merged**
