### PR TITLE
Create MIC.yaml

### PR DESCRIPTION
**Pull request by Asidert**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by Angelskii** [comment]
check the token $MIC

**Comment by qaqaric** [comment]
sir, check the token $MIC please

**Comment by Angelskii** [comment]
> sir, check the token $MIC please
How long will it take to check?

**Comment by ismahuisma** [comment]
Pls, check the token $MIC

**Comment by Alexxx543** [comment]
Hi sir, can you check token $MIC please

**Comment by amf1st** [comment]
Check $MIC token please!🧐
We have a big friendly community!

**Comment by Antoha1992** [comment]
Hello, remove the die from the microdiving token. We are people too, why wait so long?
Вообще трататули перепутали?

**Comment by Neytron322** [comment]
Actually all github users are my fakes and to prove it now I will start sending this message from all accounts!
!!! confirm $MIC !!!!

**Comment by Theodoriusss** [comment]
Hello, confirm $MIC please!

**Comment by nameport** [comment]
It seems to me that checking the $MIC token is necessary

**Comment by importage** [comment]
I vote for $mic confirmation!!!

**Comment by salateur** [comment]
The token is already added to the assets via importing from DEX.

**Pull request closed without merging**
