### PR TITLE
Update jettons.json

### PR DESCRIPTION
**Pull request by emobton**
Add EMOB logo and infos

### CODE REVIEW

**Comment by huantt** [comment]
Read the README again!
Your commit will never be merged.

**Comment by MisterZ2** [comment]
Hi guys…could you please let me back in the tg channel!? i guess you  accidentally banned me. (tg name: @misterZ2)

thx

**Comment by yoshihiyoo** [comment]
❤

**Comment by grishkanaruzhka** [comment]
https://utonic-finance.oss-ap-southeast-1.aliyuncs.com/assets/uton.png

**Comment by grishkanaruzhka** [comment]
The request has timed out. If you have any questions about token approval, please contact [@tkgregory](https://t.me/tkgregory) on Telegram for further consideration

**Pull request closed without merging**
