### PR TITLE
Update Token 69.yaml

### PR DESCRIPTION
**Pull request by mBTCoin**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Review by mBTCoin — COMMENTED** [review]
Good work

**Review by mBTCoin — COMMENTED** [review]
10/10

**Review by mBTCoin — COMMENTED** [review]
Go

**Review by mBTCoin — COMMENTED** [review]
+++

**Review by mBTCoin — COMMENTED** [review]
Korekta

**Comment by Uffynn** [comment]
They dont want to merge it

**Comment by mBTCoin** [comment]
> They dont want to merge it


Why don't they want to??

**Comment by Uffynn** [comment]
They have nobody working on this project. The TonKeeper & TonViewer projects are basically abandoned by the devs. They dont answer on any tickers on telegram, or here. Its just sad, no response, no care in the world. And also the pull requests just keep pilling up.

**Comment by Irso007** [comment]
This token has already been verified earlier

**Pull request closed without merging**
