### PR TITLE
SHWRM.yaml

### PR DESCRIPTION
**Pull request by kot04**
Dear Tonkeeper team,

We are writing to you to request verification of our token, $SHWRM (Биг Шавуха), on your platform. As a community-driven project built within the TON ecosystem, we are committed to ensuring accessibility and trust for all users.

Here is some key information about our project:

Token Address: 0:2493a672d815eadb782d669de6a403aa570fdbc008f85d6c06fe7c57b129315b

Community Link: https://t.me/SHWRM

Verification on Tonkeeper will make it easier for users to identify and interact with our token and help us build trust in the TON ecosystem.

We appreciate your attention to this request and look forward to your feedback. If any additional details are required, please do not hesitate to contact us.

Thanks!

### CODE REVIEW

**Comment by Gene090** [comment]
Hello. 
In line 2, remove the extra 'description':'. In line 3, put a space after 'image:', please

**Comment by kot04** [comment]
> Hello. In line 2, remove the extra 'description':'. In line 3, put a space after 'image:', please

good afternoon, I corrected what you said

**Comment by AlexSimakhin** [comment]
@kot04 Please change Token Address.
@Gene090 @xximwon Please check the addresses carefully.

**Comment by kot04** [comment]
> @kot04 Please change Token Address. @Gene090 @xximwon Please check the addresses carefully.

Sorry, I don’t know how the other address got there. I submitted a request to change the address. @Gene090 @xximwon

**Comment by salateur** [comment]
reverted the changes. if you wanna create a new one, make a new commit carefully.

**Pull request merged**
