### PR TITLE
Add HGX jetton

### PR DESCRIPTION
**Pull request by dannguyennhattruong**
Add HGX jetton for HangarX Project

### CODE REVIEW

**Review by Ahmitub — APPROVED** [review]

**Comment by dannguyennhattruong** [comment]
Hi @Ahmitub , i wonder when this PR will be merged. If you need any informations, feel free ping me here, thank you so much 🍻

**Comment by ghost** [comment]
48b0c653f30278af359e27da9da5083100f46af5

**Comment by dannguyennhattruong** [comment]
@

> [48b0c65](https://github.com/tonkeeper/ton-assets/commit/48b0c653f30278af359e27da9da5083100f46af5)

Is it ok?

**Comment by dannguyennhattruong** [comment]
Hi @Ahmitub, Any updates ? what i need to do? Thank you bro

**Pull request closed without merging**
