### PR TITLE
Create Catton.yaml

### PR DESCRIPTION
**Pull request by Cattontech**
Add some Catton Tokens for CattonFI (CDPs) mainnet.

Please make sure you change the original .yaml fields in the accounts/, Collections/ or jettons/ directories and leave the auto-generated .json files in the repository root alone. Also please make sure that you do not use ton.api links in your pull request.
Example pull request:

```yaml
name: the name of your token
description: description of your token
image: "link to your token logo" !!! (don't use ton.api)!!!
address: Address of your token 
symbol: Symbol of your token
websites:
  - "link"
social:
  - "link"
```

Пожалуйста, убедитесь, что вы изменили исходные поля .yaml в каталогах account/, Collections/ или jettons/ и не трогаете автоматически сгенерированные файлы .json в корне репозитория. Так же, пожалуйста, убедитесь, что вы не используете ссылки ton.api в вашем пул реквесте.
Пример пул реквеста:

```yaml
name: имя вашего токена
description: описание вашего токена
image: "ссылка на лого вашего токена" !!! (не используйте ton.api)!!!
address: Адрес вашего токена 
symbol: Сивол вашего токена
websites:
  - "ссылка"
social:
  - "ссылка"
  ```

### CODE REVIEW

**Comment by Cattontech** [comment]
Hello @Irso007,

Could you kindly review our pull request for the verification of some Catton' token for CDP protocol? Your assistance would be greatly appreciated!

Thank you in advance!

**Comment by Irso007** [comment]
We consider all pull requests in the order of the queue. Be patient, we will definitely check everything and make a decision on your pull request.

**Comment by Cattontech** [comment]
> We consider all pull requests in the order of the queue. Be patient, we will definitely check everything and make a decision on your pull request.

Thank you! We are participating in the Open League SS7. Please help us check soon so users can have tokens verified. We truly appreciate it!

**Comment by ghost** [comment]
Hi Please help me as someone's messed up my account and I have so many people asking about 
 coment or...I don't know at all about it.what can I do?I lost about 2000.00 ton coin my self.
Thank you

**Comment by Cattontech** [comment]
Hello @Irso007,

How can our project list on TonKeeper Browser ? 

Thank you in advance!

**Comment by Irso007** [comment]
For this issue, please contact Tonkeeper support in Telegram @tonkeeper

**Pull request merged**
