### PR TITLE
Create oops.yaml

### PR DESCRIPTION
**Pull request by PewPewForU**
Register for the OOPS token

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by Gene090** [comment]
Hello. Could you please clarify is the commit still required? Could you please add social media links. Is the project alive?
The requester will be closed after a week in case of inactivity. 
We apologize for the long response time.

**Comment by KrimoAti** [comment]
We're are my assets

Gene090 ***@***.***> schrieb am Mi., 27. Nov. 2024, 21:57:

**Comment by PewPewForU** [comment]
@Gene090 it's OK to close this thread, it took too long to get the review for this project, is there a way to expedite this process? this is just for me for the next venture.
Thanks!

**Comment by Irso007** [comment]
Sorry for the long wait, we will try to be faster in the future.

**Pull request closed without merging**
