### PR TITLE
Create LUCK.yaml

### PR DESCRIPTION
**Pull request by Itridiys**
Create LUCK.yaml

### CODE REVIEW

**Comment by Itridiys** [comment]
Create LUCK.yaml

**Comment by Itridiys** [comment]
please check request

**Review by Carlagaldecio — COMMENTED** [review]
Itridiys:main

**Comment by Itridiys** [comment]
what does your comment mean?

**Comment by Itridiys** [comment]
what does your comment mean?

**Comment by Itridiys** [comment]
what's wrong with the request?

**Comment by Itridiys** [comment]
what's wrong with the request?

**Comment by Itridiys** [comment]
do I need to make a request not from the main branch?

**Comment by Itridiys** [comment]
Please make sure you change the original ones .yaml fiels in directories accounts/, collections/ or jettons/ and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные .yaml файлы в директориях accounts/, collections/ или jettons/ и не трогаете автоматически сгенерированные файлы .json в корне репозитория.

**Comment by Itridiys** [comment]
name: Luckcoin
description: Your all-in-one destination for a seamless and powerful user experience on TON. TG - https://t.me/luckcointon
image: "https://cache.tonapi.io/imgproxy/vTwA5NbWlT85qNDT2Ij8KWs3mS8HxemLIg6iENEEgNA/rs:fill:200:200:1/g:no/aHR0cHM6Ly90ZXBsby52aXAvaW1hZ2UvY2FjaGUvY2F0YWxvZy81MDI5NTY0MiUyODUlMjktODAweDgwMC5wbmc.webp"
address: 0:a0ac77844baffb3bb7b5cd8493d6f093deeaf6d92a353c069f266b89c9a12433
symbol: LUCK
max_supply: 8000000000
websites:

"https://luckcointon.com/"
social:
"https://t.me/luckcointon"

**Pull request closed without merging**
