### PR TITLE
Add Lady.yaml

### PR DESCRIPTION
**Pull request by TonHelper1**
Add Lady.yaml

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by Themushroommafia** [comment]
This is a $1b narrative, don't fade the true $LADY!

**Comment by SuchaLADYonTon** [comment]
This is the scam version, I know the developer of the main LADY coin (, he also developed the whole thing before everyone else, however the LP didn't add when creating the pool, and the pool came up on a scanner bot and this scammer copied, he has awful token distribution, and is anon in telegram group.

investors don't be fooled by this, this project is a trademark scam and id like everyone to know there money isn't safe with this project

however the original LADY has a full fit team rolling out marketing every hour, they also submitted a pull request, if the Tonkeeper team could look into this and verify it that would be amazing. this is the legitimate chart (https://www.geckoterminal.com/ton/pools/EQCaKf4dfImSScJ8xfoXgCrk6detp0W0O6Sh_6dUTgJUG7rY) and this is their pull request(https://github.com/tonkeeper/ton-assets/pull/682) thank you, and stay safe investors

**Comment by Themushroommafia** [comment]
> This is the scam version, I know the developer of the main LADY coin (, he also developed the whole thing before everyone else, however the LP didn't add when creating the pool, and the pool came up on a scanner bot and this scammer copied, he has awful token distribution, and is anon in telegram group.
> 
> investors don't be fooled by this, this project is a trademark scam and id like everyone to know there money isn't safe with this project
> 
> however the original LADY has a full fit team rolling out marketing every hour, they also submitted a pull request, if the Tonkeeper team could look into this and verify it that would be amazing. this is the legitimate chart (https://www.geckoterminal.com/ton/pools/EQCaKf4dfImSScJ8xfoXgCrk6detp0W0O6Sh_6dUTgJUG7rY) and this is their pull request(#682) thank you, and stay safe investors

I'm sorry that you associate with scammers like the people who launched the fake $LADY that you linked

**Comment by SuchaLADYonTon** [comment]
this is also proof that we started first (https://www.geckoterminal.com/ton/pools/EQArIrGBlP-OoQCWGG6ahjW6nAKGUMTIczUKNllMe5KlDh-v) however we had lp issues from dedust and stone.fi side, hence why the ratio was wrong and had to start again multiple times. it only worked correctly today, yes they may have launched a few hours prior, but we had everything set up ready to go, it was just issues from the lp side

**Comment by SuchaLADYonTon** [comment]
we are not scammers, you know full well we started this whole thing off and your clinging onto it. also who are you to talk? you have an anon dev, with an awful token distribution.  where as we have a fully fit team, we already applied for all listings and even twitter premium . the investors of your coin should be thinking again

**Comment by thetruechad** [comment]
I'm with @SuchaLADYonTon on this. pls we all have to always strive to be original. May the best team win

**Comment by Irso007** [comment]
Tonkeeper reserves the right to refuse token verification.

**Pull request closed without merging**
