### PR TITLE
Create FINCH.yaml

### PR DESCRIPTION
**Pull request by ghost**
Verifying Finch Coin:

name: Finch Coin
description: Fly Beyond Limits! || finchcoin.org
image: "https://finchcoin.org/finchlogo_300.jpg"
address: 0:dd3dfe7f338e77aa06028c6d28d48d52abf252eaa097517f9391a4cd4641fe1c
symbol: FINCH
websites:
  - "https://finchcoin.org"
social:
  - "https://t.me/FinchCoin_org"
  - "https://t.me/FinchAirdropBot"
  - "https://x.com/FinchCoin_org"
geckoterminal: "https://www.geckoterminal.com/ton/pools/EQDJavCUwt_FX-hy1sj_Oc4ba5FYhx6K6937f42AKQLoIhya"
dyor: "https://dyor.io/token/EQDdPf5_M453qgYCjG0o1I1Sq_JS6qCXUX-TkaTNRkH-HLb9"
dyor: "https://dyor.io/dapps/earn/bfqnz6b95qx8"
tonraffles: "https://tonraffles.app/lock/EQDJavCUwt_FX-hy1sj_Oc4ba5FYhx6K6937f42AKQLoIhya"

### CODE REVIEW

**Comment by ghost** [comment]
Are there any updates on my request? It has been three days since I submitted it.

**Comment by KrimoAti** [comment]
I am happy

**Comment by bashtrader** [comment]
> I am happy

Sorry? Are you from the Tonviewer Team?

**Comment by ghost** [comment]
> I am happy

Are you from the Tonviewer Team?

**Comment by Irso007** [comment]
There are some issues with this request:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1436/checks#step:5:7), in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 11[8](https://github.com/tonkeeper/ton-assets/pull/1436/checks#step:5:9), in main
    jettons = merge_jettons()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 63, in merge_jettons
    raise Exception("invalid keys %s in %s" % (set(j.keys()) - ALLOWED_KEYS, j.get('name')))
Exception: invalid keys {'dyor', 'geckoterminal', 'tonraffles'} in Finch Coin


Please fix it

**Comment by ghost** [comment]
> There are some issues with this request:
> 
> ERROR:root:failed to get megaton assets Traceback (most recent call last): File "/home/runner/work/ton-assets/ton-assets/generator.py", line 17[6](https://github.com/tonkeeper/ton-assets/pull/1436/checks#step:5:7), in main() File "/home/runner/work/ton-assets/ton-assets/generator.py", line 11[8](https://github.com/tonkeeper/ton-assets/pull/1436/checks#step:5:9), in main jettons = merge_jettons() File "/home/runner/work/ton-assets/ton-assets/generator.py", line 63, in merge_jettons raise Exception("invalid keys %s in %s" % (set(j.keys()) - ALLOWED_KEYS, j.get('name'))) Exception: invalid keys {'dyor', 'geckoterminal', 'tonraffles'} in Finch Coin
> 
> Please fix it

Updated, Please check

**Pull request merged**
