### PR TITLE
add degrees.yaml to /collections

### PR DESCRIPTION
**Pull request by msilenkov**
name: Degrees°
description: Angles

→ channel @degrees, @prodegrees
→ community @degreeston
→ not clicker @prodegreesbot

/\/\/ º
image: "https://i.getgems.io/XfB09VekpTDCcqe0LoxA1QmPJIFqhYtzf7dlo0-fY58/rs:fill:200:200:1/g:ce/att:1/czM6Ly9nZXRnZW1zLW5mdC9uZnQvYy82NWZkODY0OWIzMmMxNTY5YjJiZGQwNjIvYXZhdGFyLzUxMjU4NS5zdmc"
address: "0:f2bd3b92c32358d75b6eb78e053e41b30fd3d46cd70f814ff005afb4aeecee1a"
social:
  - "https://t.me/degrees"
  - "https://t.me/degreeston"
  - "https://t.me/prodegreesbot"

### CODE REVIEW

**Comment by Irso007** [comment]
1. Incorrect request, add a detailed description of the collection, remove incorrect links like @link

2. There are some issues with this request:

ERROR:root:failed to get megaton assets
Traceback (most recent call last):
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 176, in <module>
    main()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 119, in main
    collections = merge_collections()
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 104, in merge_collections
    raw = [yaml.safe_load(open(file)) for file in sorted(glob.glob("collections/*.yaml"))]
  File "/home/runner/work/ton-assets/ton-assets/generator.py", line 104, in <listcomp>
    raw = [yaml.safe_load(open(file)) for file in sorted(glob.glob("collections/*.yaml"))]
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/__init__.py", line 12[5](https://github.com/tonkeeper/ton-assets/pull/1422/checks#step:5:6), in safe_load
    return load(stream, SafeLoader)
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/composer.py", line 3[6](https://github.com/tonkeeper/ton-assets/pull/1422/checks#step:5:7), in get_single_node
    document = self.compose_document()
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/composer.py", line 12[7](https://github.com/tonkeeper/ton-assets/pull/1422/checks#step:5:8), in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/parser.py", line 9[8](https://github.com/tonkeeper/ton-assets/pull/1422/checks#step:5:9), in check_event
    self.current_event = self.state()
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/home/runner/.local/lib/python3.10/site-packages/yaml/scanner.py", line 2[9](https://github.com/tonkeeper/ton-assets/pull/1422/checks#step:5:10)1, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "collections/degrees.yaml", line 4, column 1
could not find expected ':'
  in "collections/degrees.yaml", line 5, column 1

**Comment by msilenkov** [comment]
updated

**Comment by MXzander** [comment]
msilenkov:main

**Comment by msilenkov** [comment]
> msilenkov:main

done

**Comment by Gene090** [comment]
Hello. Thanks for the changes, could you also add more explanation to the description?

**Comment by msilenkov** [comment]
> Hello. Thanks for the changes, could you also add more explanation to the description?

Done. Added to degrees.yaml.

**Comment by Gene090** [comment]
Thanks for the update. Have a nice day!

**Pull request merged**
