### PR TITLE
verification of $RPC jetton

### PR DESCRIPTION
**Pull request by ton-rpc-dev**
Request to verify token RPC, added RPC.yaml

### CODE REVIEW

**Comment by ton-rpc-dev** [comment]
can you give approve?

**Comment by ghost** [comment]
1048

**Comment by ghost** [comment]
No I don't know what to do

**Comment by Irso007** [comment]
If you still need verification process, please let us know in this pull request or else it will be closed in a week.

**Comment by Irso007** [comment]
If your request is relevant, create a new request.

**Pull request closed without merging**
