### PR TITLE
DOGWIFHOOD.yaml

### PR DESCRIPTION
**Pull request by dogwifhood**
Hello,

Please consider adding DOGWIFHOOD to the list of supported/verified jettons on tonkeeper!

Thank you!

### CODE REVIEW

**Comment by Kafarion** [comment]
WTF, how did you get verified so quickly?

**Comment by dogwifhood** [comment]
@Kafarion It's only verified by an automatic thing. It's not yet merged!

**Comment by vladus-dev** [comment]
@dogwifhood today is merged?

**Comment by dogwifhood** [comment]
@Kafarion @vladus-dev @oleganza @brainpicture @Spetsnaz116 sorry for pinging you all but was wondering what's wrong with our PR and why it hasn't been merged yet. 

Some of our supporters are asking why are asking why aren't we listed. 

Thank you!

**Pull request closed without merging**
