### PR TITLE
Create UTYA.yaml

### PR DESCRIPTION
**Pull request by ton-lover**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by ton-lover** [comment]
Hi, When approved please maintainer :) (@oleganza  @brainpicture  @behrang  @vladzima) ? Pavel is waiting for it hehe https://twitter.com/TonUtyacoin/status/1781302107271761923

Привет, когда будет одобрено, пожалуйста, добавьте в участники :) (@oleganza @brainpicture @behrang @vladzima)? Павел ждет это, хе-хе https://twitter.com/TonUtyacoin/status/1781302107271761923

**Comment by TangerineNe** [comment]
Is it copy of $DUCK?
Это копия $DUCK? 
Original: https://duck-coin.com/

**Comment by norbekoff** [comment]
I think it is a scam project since there is already [$duck](https://tonviewer.com/0:53732b598dd67014b8fa4ceec2786be7e1a326a97bdb5fe9ce0e20296ddd35d6)

**Comment by Themaster78** [comment]
$Duck is the SCAM, be careful. The dev own 40% of token and are silent in the télégram. BE CAREFUL DUCK IS THE SCAM !

**Comment by vipera7** [comment]
$DUCK is the scam here. $UTYA is the official

**Comment by alexchaikovsky** [comment]
$UTYA is a scam copy of $DUCK! Beware!

**Comment by Volaheck** [comment]
> $DUCK is the scam here. $UTYA is the official

None of these jettons are official. But UTYA is a pure copy of DUCK

**Comment by leshthetnyy** [comment]
$DUCK - is original. The rest has nothing to do with him. Pavel Durov himself said this at TOKEN 2049.

**Comment by xmaslo3b** [comment]
$UTYA is fake token. Low quality copy of $DUCK.

**Comment by asadullakkh** [comment]
$UTYA is a scam, using the original stickers of $DUCK, and convincing others that they are the real ones. 

The OG is $DUCK❗️

[duck-coin.com](https://duck-coin.com)
https://x.com/notduckcoin?s=21
https://t.me/duckcoin

**Comment by ton-lover** [comment]
Not a scam at all, Pavel talked about us lol

**Comment by Volaheck** [comment]
> Not a scam at all, Pavel talked about us lol

Why not about duck?) UTYA is copy of DUCK
Pavel talked about stickers, but not about jettons

**Comment by the0ry1337** [comment]
UTYA is a personal name of the telegram duck, this project is 100% community driven and hence can not be a scam. I hope it gets verified soon!

**Comment by Sivvy209** [comment]
$Duck is the scam project! Look at the dev supply and the activity with the community. Dev owns 40%!!!! $UTYA has done nothing against them and they continuously try to harm a community takeover project. Instead of worrying bout themselves and their own token, which is pretty much dead, they wish to do harm against others.

**Comment by Volaheck** [comment]
> $Duck is the scam project! Look at the dev supply and the activity with the community. Dev owns 40%!!!! $UTYA has done nothing against them and they continuously try to harm a community takeover project. Instead of worrying bout themselves and their own token, which is pretty much dead, they wish to do harm against others.

"Token's name or image can lead users into deception"

**Comment by norbekoff** [comment]
> $Duck is the scam project! Look at the dev supply and the activity with the community. Dev owns 40%!!!! $UTYA has done nothing against them and they continuously try to harm a community takeover project. Instead of worrying bout themselves and their own token, which is pretty much dead, they wish to do harm against others.

I wonder why this github account was created 2 hours ago?)

**Review by Greb0wski — APPROVED** [review]
I see no issues with approving this. I would add that any comments that are focussed on or comparing to other jettons are irrelevant and seem to be unfounded. We surely want all TON jettons to succeed.

**Comment by Volaheck** [comment]
> I see no issues with approving this. I would add that any comments that are focussed on or comparing to other jettons are irrelevant and seem to be unfounded. We surely want all TON jettons to succeed.


It is very important not to mislead users. By making tokens look very similar, we are essentially creating a scam, as people can easily get confused. Even in the Tonkeeper wallet, there is a criterion for unverified tokens: "Token name or image can lead users into deception". And this token is misleading, with its name and image being very similar to the duck token. That is why comparison is important and appropriate.

**Comment by Greb0wski** [comment]
> > I see no issues with approving this. I would add that any comments that are focussed on or comparing to other jettons are irrelevant and seem to be unfounded. We surely want all TON jettons to succeed.
> 
> It is very important not to mislead users. By making tokens look very similar, we are essentially creating a scam, as people can easily get confused. Even in the Tonkeeper wallet, there is a criterion for unverified tokens: "Token name or image can lead users into deception". And this token is misleading, with its name and image being very similar to the duck token. That is why comparison is important and appropriate.

Completely agree. But this is a community takeover token with a different name and a different focus entirely. They also have different tickers and main image. It is clearly not a copycat but instead a completely different token. No one accuses doge or shib or floki to be copies of an earlier token called ‘dog’. 
Geckoterminal sees no confusion, placing the two coins in completely different categories (Utya is in ‘sticker’ -https://www.geckoterminal.com/category/sticker), whereas Duck seems to be in no category. The official ton_blockchain X account also sees no confusion, calling Utya by their actual name (https://x.com/ton_blockchain/status/1782494152308986041). Indeed, the only attempt to mislead users appears to be from commentators incorrectly suggesting that Utya is a scam, providing no evidence and ignoring the fact that it is community run and owned. I would have hoped that the TON community would have been better and rallied to celebrate all tokens on the chain as we seek to welcome new entrants.

**Comment by Volaheck** [comment]
> > > I see no issues with approving this. I would add that any comments that are focussed on or comparing to other jettons are irrelevant and seem to be unfounded. We surely want all TON jettons to succeed.
> > 
> > 
> > It is very important not to mislead users. By making tokens look very similar, we are essentially creating a scam, as people can easily get confused. Even in the Tonkeeper wallet, there is a criterion for unverified tokens: "Token name or image can lead users into deception". And this token is misleading, with its name and image being very similar to the duck token. That is why comparison is important and appropriate.
> 
> Completely agree. But this is a community takeover token with a different name and a different focus entirely. They also have different tickers and main image. It is clearly not a copycat but instead a completely different token. No one accuses doge or shib or floki to be copies of an earlier token called ‘dog’. Geckoterminal sees no confusion, placing the two coins in completely different categories (Utya is in ‘sticker’ -https://www.geckoterminal.com/category/sticker), whereas Duck seems to be in no category. The official ton_blockchain X account also sees no confusion, calling Utya by their actual name (https://x.com/ton_blockchain/status/1782494152308986041). Indeed, the only attempt to mislead users appears to be from commentators incorrectly suggesting that Utya is a scam, providing no evidence and ignoring the fact that it is community run and owned. I would have hoped that the TON community would have been better and rallied to celebrate all tokens on the chain as we seek to welcome new entrants.


UTYA - It really looks like a scam. They explicitly and seriously claim that Pavel Durov specifically mentioned them and try to present themselves as some sort of official token that Durov supports. Also, the dog-based tokens listed above have completely different foundational ideas. Here, it's literally plagiarism. I support new projects. But plagiarism and lies are not good.

**Comment by Greb0wski** [comment]
> > > > I see no issues with approving this. I would add that any comments that are focussed on or comparing to other jettons are irrelevant and seem to be unfounded. We surely want all TON jettons to succeed.
> > > 
> > > 
> > > It is very important not to mislead users. By making tokens look very similar, we are essentially creating a scam, as people can easily get confused. Even in the Tonkeeper wallet, there is a criterion for unverified tokens: "Token name or image can lead users into deception". And this token is misleading, with its name and image being very similar to the duck token. That is why comparison is important and appropriate.
> > 
> > 
> > Completely agree. But this is a community takeover token with a different name and a different focus entirely. They also have different tickers and main image. It is clearly not a copycat but instead a completely different token. No one accuses doge or shib or floki to be copies of an earlier token called ‘dog’. Geckoterminal sees no confusion, placing the two coins in completely different categories (Utya is in ‘sticker’ -https://www.geckoterminal.com/category/sticker), whereas Duck seems to be in no category. The official ton_blockchain X account also sees no confusion, calling Utya by their actual name (https://x.com/ton_blockchain/status/1782494152308986041). Indeed, the only attempt to mislead users appears to be from commentators incorrectly suggesting that Utya is a scam, providing no evidence and ignoring the fact that it is community run and owned. I would have hoped that the TON community would have been better and rallied to celebrate all tokens on the chain as we seek to welcome new entrants.
> 
> UTYA - It really looks like a scam. They explicitly and seriously claim that Pavel Durov specifically mentioned them and try to present themselves as some sort of official token that Durov supports. Also, the dog-based tokens listed above have completely different foundational ideas. Here, it's literally plagiarism. I support new projects. But plagiarism and lies are not good.

Respectfully, you provide no evidence for your assertions. I still do not understand how you can consider a community takeover token to be ‘literally plagiarism’ - you imply malice where there is none. They make no claim with regards to Pavel - no more so than $Duck, as shown here - https://x.com/notduckcoin/status/1781575894282199369
I really would suggest that people’s efforts are best spent moving the whole space forward and not trying to pull other projects down.

**Comment by Volaheck** [comment]
> > > > > I see no issues with approving this. I would add that any comments that are focussed on or comparing to other jettons are irrelevant and seem to be unfounded. We surely want all TON jettons to succeed.
> > > > 
> > > > 
> > > > It is very important not to mislead users. By making tokens look very similar, we are essentially creating a scam, as people can easily get confused. Even in the Tonkeeper wallet, there is a criterion for unverified tokens: "Token name or image can lead users into deception". And this token is misleading, with its name and image being very similar to the duck token. That is why comparison is important and appropriate.
> > > 
> > > 
> > > Completely agree. But this is a community takeover token with a different name and a different focus entirely. They also have different tickers and main image. It is clearly not a copycat but instead a completely different token. No one accuses doge or shib or floki to be copies of an earlier token called ‘dog’. Geckoterminal sees no confusion, placing the two coins in completely different categories (Utya is in ‘sticker’ -https://www.geckoterminal.com/category/sticker), whereas Duck seems to be in no category. The official ton_blockchain X account also sees no confusion, calling Utya by their actual name (https://x.com/ton_blockchain/status/1782494152308986041). Indeed, the only attempt to mislead users appears to be from commentators incorrectly suggesting that Utya is a scam, providing no evidence and ignoring the fact that it is community run and owned. I would have hoped that the TON community would have been better and rallied to celebrate all tokens on the chain as we seek to welcome new entrants.
> > 
> > 
> > UTYA - It really looks like a scam. They explicitly and seriously claim that Pavel Durov specifically mentioned them and try to present themselves as some sort of official token that Durov supports. Also, the dog-based tokens listed above have completely different foundational ideas. Here, it's literally plagiarism. I support new projects. But plagiarism and lies are not good.
> 
> Respectfully, you provide no evidence for your assertions. I still do not understand how you can consider a community takeover token to be ‘literally plagiarism’ - you imply malice where there is none. They make no claim with regards to Pavel - no more so than $Duck, as shown here - https://x.com/notduckcoin/status/1781575894282199369 I really would suggest that people’s efforts are best spent moving the whole space forward and not trying to pull other projects down.


In the provided source, there were no false statements. DUCK really uses stickers as a mascot. But what proof is expected from my side if it can be seen in the very first comment in this thread?


image

**Comment by Volaheck** [comment]
The only things I advocate for here are:
-That people don't lie when launching their projects.
-That people launch unique projects, not copies of others.
In this case, the projects are really very easy to confuse.

**Comment by Greb0wski** [comment]
> The only things I advocate for here are: -That people don't lie when launching their projects. -That people launch unique projects, not copies of others. In this case, the projects are really very easy to confuse.

Once again you imply malice where there is none. This thread was created by a community member, not by any of the original team or current admins. The community had no control over the launch of this project. To attempt to drag down a community is such a disappointing reaction - you give zero evidence of the likelihood of confusion. I also find it disingenuous that no such commentary has been raised against $TONY - when you search for duck and ton on X the Tony account is the only result. 
it is clear we disagree, but I very much question your motives in providing these objections.

**Comment by Volaheck** [comment]
> Once again you imply malice where there is none. This thread was created by a community member, not by any of the original team or current admins. The community had no control over the launch of this project. To attempt to drag down a community is such a disappointing reaction - you give zero evidence of the likelihood of confusion. I also find it disingenuous that no such commentary has been raised against $TONY - when you search for duck and ton on X the Tony account is the only result.
> it is clear we disagree, but I very much question your motives in providing these objections.

All the reasons for my objections have been described above. I'm not implying anything; I'm making direct statements. Everyone can assess the likelihood of confusion on their own; it doesn't require any proof.
Additionally, I provided evidence of the lies in the screenshot above. Upon request, I can provide more screenshots of false statements that mislead the community.

**Comment by Sivvy209** [comment]
Very sad how some people want to bring down another community who has done nothing to them. A community who minds their business, sticks together, and has brought no harm to others. 

And for people who say it can be deceiving cause both tokens look similar, that is a lie. One of the basic principles in buying crypto is buying the right contract. Also the main images of each token are very different that anyone can see the difference.

**Comment by UTyalover** [comment]
> Hi, When approved please maintainer :) (@oleganza @brainpicture @behrang @vladzima) ? Pavel is waiting for it hehe https://twitter.com/TonUtyacoin/status/1781302107271761923
> 
> Привет, когда будет одобрено, пожалуйста, добавьте в участники :) (@oleganza @brainpicture @behrang @vladzima)? Павел ждет это, хе-хе https://twitter.com/TonUtyacoin/status/1781302107271761923

I love utya, it's a community owned token that focuses on creating a fun, diverse and strong community. There are some negative comments but you guys can easily trace and see who they are lol, just be careful of the other ones, they rather focus on attacking utya than focusing on empowering their own token which is clearly a red flag.

**Comment by thenoja** [comment]
> There are some negative comments but you guys can easily trace and see who they are lol

@UTyalover This doesn’t really sound convincing considering your account is 1 hour old.

As for the Utya it is very obvious: "Token’s name or image can lead users into deception". Please show some respect for other projects by staying away from cloning. It's utterly disrespectful, unethical and lacks originality.

**Review by thenoja — CHANGES_REQUESTED** [review]
The project's resemblance to  [$duck](https://tonviewer.com/0:53732b598dd67014b8fa4ceec2786be7e1a326a97bdb5fe9ce0e20296ddd35d6) is concerning, especially considering TonKeeper's warning about potential user deception.


> Used for scam. Token's name or image can lead
users into deception.

 Without addressing this lack of originality, approval for the project cannot be granted.

**Comment by Greb0wski** [comment]
> > There are some negative comments but you guys can easily trace and see who they are lol
> 
> @UTyalover This doesn’t really sound convincing considering your account is 1 hour old.
> 
> As for the Utya it is very obvious: "Token’s name or image can lead users into deception". Please show some respect for other projects by staying away from cloning. It's utterly disrespectful, unethical and lacks originality.

You’re acting like the people commenting here made the token. They didn’t. The community came together to celebrate a particular token and a particularly named project. Comments such as yours show a distinct lack of understanding and attempt to undermine and erode the ideals of cryptocurrency and the Open Network ethos and ecostructure. A disappointing response.

**Comment by Volaheck** [comment]
> > > There are some negative comments but you guys can easily trace and see who they are lol
> > 
> > 
> > @UTyalover This doesn’t really sound convincing considering your account is 1 hour old.
> > As for the Utya it is very obvious: "Token’s name or image can lead users into deception". Please show some respect for other projects by staying away from cloning. It's utterly disrespectful, unethical and lacks originality.
> 
> You’re acting like the people commenting here made the token. They didn’t. The community came together to celebrate a particular token and a particularly named project. Comments such as yours show a distinct lack of understanding and attempt to undermine and erode the ideals of cryptocurrency and the Open Network ethos and ecostructure. A disappointing response.


There are many unsubstantiated statements. We are all part of the community here, and we all stand for something. As I wrote above, it is important that new projects do not lie, do not mislead their community, and are unique. There is no need to create copies of projects, be original. There is no need to lie when launching your projects, be honest with your community.

We also did not launch $DUCK, but we advocate no less than what I described above, and no more than what I described above. No one is attacking anyone, and nothing is undermining.

We are all just expressing our opinion. And we believe that what we stand for can make the TON ecosystem better.

There are many copies, such as:
utya, aytu, black duck, kcud, etc.
It is advisable to motivate the community not to create copies, but to create something original, without copying others.

**Comment by humanbeingonearth** [comment]
The fact that anyone is coming into here to create FUD about another project is sad. 

The fact that you are falling for it @thenoja is even worse.
Can you please just put your biases aside and approve this project on the merit of itself, not some random FUD by random people.

These people are probably too sour that their beloved project is 2.5x below starting price.  All you have to do is research the duck token for two seconds and see that the chart clearly represents a presale exit, and the community is in shambles if they have to come here to FUD. 

duck-chart

**Comment by Volaheck** [comment]
> The fact that anyone is coming into here to create FUD about another project is sad.
> 
> The fact that you are falling for it @thenoja is even worse. Can you please just put your biases aside and approve this project on the merit of itself, not some random FUD by random people.
> 
> These people are probably too sour that their beloved project is 2.5x below starting price. All you have to do is research the duck token for two seconds and see that the chart clearly represents a presale exit, and the community is in shambles if they have to come here to FUD.
> 
> duck-chart

There is nothing sad about expressing your opinion. You can't call constructive criticism FUD just because you don't like it. It is important to be able to accept criticism. No FUD were voiced. Everyone noticed what they thought was important. And everyone has contributed to the community. It is worth respecting the opinion of the community, and not calling it FUD, because it does not coincide with yours and price of the token does not relate to the discussion in any way. We are the same community, and we want to see high-quality projects that are not based on lies and copying others

**Comment by Greb0wski** [comment]
> > The fact that anyone is coming into here to create FUD about another project is sad.
> > The fact that you are falling for it @thenoja is even worse. Can you please just put your biases aside and approve this project on the merit of itself, not some random FUD by random people.
> > These people are probably too sour that their beloved project is 2.5x below starting price. All you have to do is research the duck token for two seconds and see that the chart clearly represents a presale exit, and the community is in shambles if they have to come here to FUD.
> > duck-chart
> 
> There is nothing sad about expressing your opinion. You can't call constructive criticism FUD just because you don't like it. It is important to be able to accept criticism. No FUD were voiced. Everyone noticed what they thought was important. And everyone has contributed to the community. It is worth respecting the opinion of the community, and not calling it FUD, because it does not coincide with yours and price of the token does not relate to the discussion in any way. We are the same community, and we want to see high-quality projects that are not based on lies and copying others

Lies? No one arguing for the validity of this request is lying. I fail to see how you can not appreciate that Utya is a high-quality project. Ton clearly can…
https://twitter.com/ton_blockchain/status/1784863095543722067
If the official TON blockchain X account can recognise UTYA as a valid and authentic Jetton then this conversation is effectively over.

**Comment by Volaheck** [comment]
> Lies? No one arguing for the validity of this request is lying. I fail to see how you can not appreciate that Utya is a high-quality project. Ton clearly can… https://twitter.com/ton_blockchain/status/1784863095543722067 If the official TON blockchain X account can recognise UTYA as a valid and authentic Jetton then this conversation is effectively over.

I don't see the point in repeating myself. Personally, like many people here, this one is not considered high-quality. And why - everything was said above.

**Comment by grishkanaruzhka** [comment]
The request has timed out. If you have any questions about token approval, please contact [@tkgregory](https://t.me/tkgregory) on Telegram for further consideration

**Pull request closed without merging**
