### PR TITLE
Create TMONKEY jettons yaml

### PR DESCRIPTION
**Pull request by lacostenycoder**
ref #926 

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.
TMONKEY

### CODE REVIEW

**Comment by Uffynn** [comment]
Its pointless, nobody check the repositories

**Comment by lacostenycoder** [comment]
> Its pointless, nobody check the repositories

you could just upvote though, wouldn't kill you lol

**Comment by lacostenycoder** [comment]
@grishkanaruzhka
I see you merge others like this. What is the secret to getting this merged?

**Comment by lacostenycoder** [comment]
@tawhidnazari57 how do we get you to review this so we can get it merged?

**Comment by lacostenycoder** [comment]
@glook can I ask what magic was used to get [your PR](https://github.com/tonkeeper/ton-assets/pull/949) approved and merged?

**Comment by lacostenycoder** [comment]
@TrustTonDev can you help with this somehow?

**Review by tawhidnazari57 — APPROVED** [review]

**Comment by lacostenycoder** [comment]
@tawhidnazari57 THANK YOU!!!!!!!

**Review by tawhidnazari57 — APPROVED** [review]

**Review by mm8191 — APPROVED** [review]

**Review by mm8191 — APPROVED** [review]

**Review by Hamaster2 — APPROVED** [review]

**Comment by Irso007** [comment]
Inactive token

**Comment by lacostenycoder** [comment]
> Inactive token

No it's not inactive, it's just been dormant.  But we need help getting Ton Keeper to stop showing it as unknown.

**Comment by Uffynn** [comment]
What does inactivity have to do with a token being shown as unknown or not?

**Pull request closed without merging**
