### PR TITLE
cash up ama radio

### PR DESCRIPTION
**Pull request by Coyote-A**
Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

### CODE REVIEW

**Comment by Sykyba89** [comment]
verification)))) please))) very much requested)))

**Comment by Sykyba89** [comment]
verification)))) please))) very much requested)))

**Comment by PRT5** [comment]
Please😜

**Comment by Sykyba89** [comment]
We do verification, quickly, with feeling, with arrangement)))))

**Comment by Sykyba89** [comment]
We do verification, quickly, with feeling, with arrangement)))))

**Comment by Sykyba89** [comment]
We kindly ask you to speed up the verification) sincerely.

**Comment by backple4se** [comment]
Faster verification will ensure maximum audience retention and increase our trust in people

**Comment by Irso007** [comment]
This token has already been verified earlier

**Pull request closed without merging**
