### PR TITLE
Update for PaperPlane.yml

### PR DESCRIPTION
**Pull request by paperplaneonton**
update image url.

### CODE REVIEW

**Comment by aleksej-paschenko** [comment]
Thank you for contributing this. 

I've noticed that there are two different telegram groups: one in this request https://t.me/paperplane_ton and another one in the blockchain https://t.me/PaperPlaneTON.

It would be great to understand why there are two different groups

**Comment by paperplaneonton** [comment]
Hey our project is a community takeover so on blockchain its old tg created
by the dev.


pt., 8 mar 2024, 10:58 użytkownik aleksej.paschenko <
***@***.***> napisał:

**Comment by bTokman** [comment]
@aleksej-paschenko https://t.me/PaperPlaneTON - was created by the dev on the first day of token creation and the last post was on the same day, the group in request (https://t.me/paperplane_ton) - a community group that contains ~800 members (the count of token holders almost the same [you can check it](https://tonviewer.com/0:17f49eb4bdafb4c080cc76a18b44c7fb8a626f1b462dca2dd8c67abdcbe9db34?section=holders)) and it shows growing

As a community, we were verified token on Ston.fi. The token community shows growth and provides AMA sessions, different events, and collaborations with other mem coins (all this you can find on [Twitter](https://twitter.com/paperplane_ton) that was provided in mr).
The token also has its own game you can find it on the main [project website](https://paperplanetoken.site/) (it is also provided in mr)

So please help us to make our community better)

**Comment by bTokman** [comment]
Hey, mr @aleksej-paschenko will you give some feedback?

**Comment by Dayjo** [comment]
I for one would very much love to see this merged in soon @aleksej-paschenko - the data in the PR is accurate.

**Comment by paperplaneonton** [comment]
@oleganza Could you help us a little bit ?

**Pull request closed without merging**
